#!/bin/bash

export MKL_NUM_THREADS=3
export OPENBLAS_NUM_THREADS=3
export OMP_NUM_THREADS=3

python lyapunov/run.py $(cat examples/args/MNIST/cc/00.txt) &
python lyapunov/run.py $(cat examples/args/MNIST/cc/01.txt) &
python lyapunov/run.py $(cat examples/args/MNIST/cc/02.txt) &
python lyapunov/run.py $(cat examples/args/MNIST/cc/03.txt) &
python lyapunov/run.py $(cat examples/args/MNIST/cc/04.txt) &
python lyapunov/run.py $(cat examples/args/MNIST/cc/05.txt) &
python lyapunov/run.py $(cat examples/args/MNIST/cc/06.txt) &
python lyapunov/run.py $(cat examples/args/MNIST/cc/07.txt) &
python lyapunov/run.py $(cat examples/args/MNIST/cc/08.txt) &
python lyapunov/run.py $(cat examples/args/MNIST/cc/09.txt) &
python lyapunov/run.py $(cat examples/args/MNIST/con/00.txt) &
python lyapunov/run.py $(cat examples/args/MNIST/con/01.txt) &
python lyapunov/run.py $(cat examples/args/MNIST/con/02.txt) &
python lyapunov/run.py $(cat examples/args/MNIST/con/03.txt) &
python lyapunov/run.py $(cat examples/args/MNIST/con/04.txt) &
python lyapunov/run.py $(cat examples/args/MNIST/con/05.txt) &
python lyapunov/run.py $(cat examples/args/MNIST/con/06.txt) &
python lyapunov/run.py $(cat examples/args/MNIST/con/07.txt) &
python lyapunov/run.py $(cat examples/args/MNIST/con/08.txt) &
python lyapunov/run.py $(cat examples/args/MNIST/con/09.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/cc/00.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/cc/01.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/cc/02.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/cc/03.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/cc/04.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/cc/05.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/cc/06.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/cc/07.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/cc/08.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/cc/09.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/cc/21.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/cc/22.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/cc/23.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/cc/24.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/cc/25.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/cc/26.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/cc/27.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/cc/28.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/cc/29.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/cc/30.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/cc/31.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/cc/32.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/cc/33.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/cc/34.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/cc/35.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/cc/36.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/cc/37.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/cc/38.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/cc/39.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/cc/40.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/cc/41.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/cc/42.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/cc/43.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/cc/44.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/cc/45.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/cc/46.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/cc/47.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/cc/48.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/cc/49.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/cc/50.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/cc/51.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/cc/52.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/con/20.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/con/21.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/con/22.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/con/23.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/con/24.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/con/25.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/con/26.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/con/27.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/con/28.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/con/29.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/con/30.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/con/31.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/reg/20.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/reg/21.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/reg/22.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/reg/23.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/reg/24.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/reg/25.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/reg/26.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/reg/27.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/reg/28.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/reg/29.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/reg/30.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/reg/31.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/reg_alt/20.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/reg_alt/21.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/reg_alt/22.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/reg_alt/23.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/reg_alt/24.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/reg_alt/25.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/reg_alt/26.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/reg_alt/27.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/reg_alt/28.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/reg_alt/29.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/reg_alt/30.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/reg_alt/31.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/simgd/20.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/simgd/21.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/simgd/22.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/simgd/23.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/simgd/24.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/simgd/25.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/simgd/26.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/simgd/27.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/simgd/28.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/simgd/29.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/simgd/30.txt) &
# python lyapunov/run.py $(cat examples/args/MO25G/simgd/31.txt) &
# python run.py $(cat args/cc/exp-cc-10.txt) &
# python run.py $(cat args/cc/exp-cc-11.txt) &
# python run.py $(cat args/cc/exp-cc-12.txt) &
# python run.py $(cat args/cc/exp-cc-13.txt) &
# python run.py $(cat args/cc/exp-cc-14.txt) &
# python run.py $(cat args/cc/exp-cc-15.txt) &
# python run.py $(cat args/cc/exp-cc-16.txt) &
# python run.py $(cat args/cc/exp-cc-17.txt) &
# python run.py $(cat args/cc/exp-cc-18.txt) &
# python run.py $(cat args/cc/exp-cc-19.txt) &
# python run.py $(cat args/cc/exp-cc-20.txt) &
# python run.py $(cat args/cc/exp-cc-21.txt) &
# python run.py $(cat args/cc/exp-cc-22.txt) &
# python run.py $(cat args/cc/exp-cc-23.txt) &
# python run.py $(cat args/cc/exp-cc-24.txt) &
# python run.py $(cat args/cc/exp-cc-25.txt) &
# python run.py $(cat args/cc/exp-cc-26.txt) &
# python run.py $(cat args/cc/exp-cc-27.txt) &
# python run.py $(cat args/cc/exp-cc-28.txt) &
# python run.py $(cat args/cc/exp-cc-29.txt) &
# python run.py $(cat args/cc/exp-cc-30.txt) &
# python run.py $(cat args/cc/exp-cc-31.txt) &
# python run.py $(cat args/cc/exp-cc-32.txt) &
# python run.py $(cat args/cc/exp-cc-33.txt) &
# python run.py $(cat args/cc/exp-cc-34.txt) &
# python run.py $(cat args/cc/exp-cc-35.txt) &
# python run.py $(cat args/cc/exp-cc-36.txt) &
# python run.py $(cat args/cc/exp-cc-37.txt) &
# python run.py $(cat args/cc/exp-cc-38.txt) &
# python run.py $(cat args/cc/exp-cc-39.txt) &
# python run.py $(cat args/cc/exp-cc-40.txt) &
# python run.py $(cat args/cc/exp-cc-41.txt) &
# python run.py $(cat args/cc/exp-cc-42.txt) &
# python run.py $(cat args/cc/exp-cc-43.txt) &
# python run.py $(cat args/cc/exp-cc-44.txt) &
# python run.py $(cat args/cc/exp-cc-45.txt) &
# python run.py $(cat args/cc/exp-cc-46.txt) &
# python run.py $(cat args/cc/exp-cc-47.txt) &
# python run.py $(cat args/cc/exp-cc-48.txt) &
# python run.py $(cat args/cc/exp-cc-49.txt) &
# python run.py $(cat args/cc/exp-cc-50.txt) &
# python run.py $(cat args/cc/exp-cc-51.txt) &
# python run.py $(cat args/cc/exp-cc-52.txt) &
# python run.py $(cat args/cc/exp-cc-53.txt) &
# python run.py $(cat args/cc/exp-cc-54.txt) &
# python run.py $(cat args/cc/exp-cc-55.txt) &
# python run.py $(cat args/cc/exp-cc-56.txt) &
# python run.py $(cat args/cc/exp-cc-57.txt) &
# python run.py $(cat args/cc/exp-cc-58.txt) &
# python run.py $(cat args/cc/exp-cc-59.txt) &
# python run.py $(cat args/cc/exp-cc-60.txt) &
# python run.py $(cat args/cc/exp-cc-61.txt) &
# python run.py $(cat args/cc/exp-cc-62.txt) &
# python run.py $(cat args/cc/exp-cc-63.txt) &
# python run.py $(cat args/cc/exp-cc-64.txt) &
# python run.py $(cat args/cc/exp-cc-65.txt) &
# python run.py $(cat args/cc/exp-cc-66.txt) &
# python run.py $(cat args/cc/exp-cc-67.txt) &
# python run.py $(cat args/cc/exp-cc-68.txt) &
# python run.py $(cat args/cc/exp-cc-69.txt) &
# python run.py $(cat args/cc/exp-cc-70.txt) &
# python run.py $(cat args/cc/exp-cc-71.txt) &
# python run.py $(cat args/con/exp-con-01.txt) &
# python run.py $(cat args/con/exp-con-02.txt) &
# python run.py $(cat args/con/exp-con-03.txt) &
# python run.py $(cat args/con/exp-con-04.txt) &
# python run.py $(cat args/con/exp-con-05.txt) &
# python run.py $(cat args/con/exp-con-06.txt) &
# python run.py $(cat args/con/exp-con-07.txt) &
# python run.py $(cat args/con/exp-con-08.txt) &
# python run.py $(cat args/con/exp-con-09.txt) &
# python run.py $(cat args/con/exp-con-10.txt) &
# python run.py $(cat args/con/exp-con-11.txt) &
# python run.py $(cat args/con/exp-con-12.txt) &
# python run.py $(cat args/con/exp-con-13.txt) &
# python run.py $(cat args/con/exp-con-14.txt) &
# python run.py $(cat args/con/exp-con-15.txt) &
# python run.py $(cat args/con/exp-con-16.txt) &
# python run.py $(cat args/con/exp-con-17.txt) &
# python run.py $(cat args/con/exp-con-18.txt) &
# python run.py $(cat args/con/exp-con-19.txt) &
# python run.py $(cat args/con/exp-con-20.txt) &
# python run.py $(cat args/con/exp-con-21.txt) &
# python run.py $(cat args/con/exp-con-22.txt) &
# python run.py $(cat args/con/exp-con-23.txt) &
# python run.py $(cat args/con/exp-con-24.txt) &
# python run.py $(cat args/con/exp-con-25.txt) &
# python run.py $(cat args/con/exp-con-26.txt) &
# python run.py $(cat args/lin/exp-lin-01.txt) &
# python run.py $(cat args/lin/exp-lin-02.txt) &
# python run.py $(cat args/lin/exp-lin-03.txt) &
# python run.py $(cat args/lin/exp-lin-04.txt) &
# python run.py $(cat args/lin/exp-lin-05.txt) &
# python run.py $(cat args/lin/exp-lin-06.txt) &
# python run.py $(cat args/lin/exp-lin-07.txt) &
# python run.py $(cat args/lin/exp-lin-08.txt) &
# python run.py $(cat args/lin/exp-lin-09.txt) &
# python run.py $(cat args/lin/exp-lin-10.txt) &
# python run.py $(cat args/lin/exp-lin-11.txt) &
# python run.py $(cat args/lin/exp-lin-12.txt) &
# python run.py $(cat args/simgd/exp-simgd-01.txt) &
# python run.py $(cat args/simgd/exp-simgd-02.txt) &
# python run.py $(cat args/simgd/exp-simgd-03.txt) &
# python run.py $(cat args/simgd/exp-simgd-04.txt) &
# python run.py $(cat args/simgd/exp-simgd-05.txt) &
# python run.py $(cat args/simgd/exp-simgd-06.txt) &
# python run.py $(cat args/simgd/exp-simgd-07.txt) &
# python run.py $(cat args/simgd/exp-simgd-08.txt) &
# python run.py $(cat args/simgd/exp-simgd-09.txt) &
# python run.py $(cat args/simgd/exp-simgd-10.txt) &
# python run.py $(cat args/reg/exp-reg-01.txt) &
# python run.py $(cat args/reg/exp-reg-02.txt) &
# python run.py $(cat args/reg/exp-reg-03.txt) &
# python run.py $(cat args/reg/exp-reg-04.txt) &
# python run.py $(cat args/reg/exp-reg-05.txt) &
# python run.py $(cat args/reg/exp-reg-06.txt) &
# python run.py $(cat args/reg/exp-reg-07.txt) &
# python run.py $(cat args/reg/exp-reg-08.txt) &
# python run.py $(cat args/reg/exp-reg-09.txt) &
# python run.py $(cat args/reg/exp-reg-10.txt) &
# python run.py $(cat args/reg/exp-reg-11.txt) &
# python run.py $(cat args/reg/exp-reg-12.txt) &
# python run.py $(cat args/reg/exp-reg-13.txt) &
# python run.py $(cat args/reg/exp-reg-14.txt) &
# python run.py $(cat args/reg/exp-reg-15.txt) &
# python run.py $(cat args/reg/exp-reg-16.txt) &
# python run.py $(cat args/reg/exp-reg-17.txt) &
# python run.py $(cat args/reg/exp-reg-18.txt) &
# python run.py $(cat args/reg/exp-reg-19.txt) &
# python run.py $(cat args/reg/exp-reg-20.txt) &
# python run.py $(cat args/reg/exp-reg-21.txt) &
# python run.py $(cat args/reg/exp-reg-22.txt) &
# python run.py $(cat args/reg/exp-reg-23.txt) &
# python run.py $(cat args/reg/exp-reg-24.txt) &
# python run.py $(cat args/reg/exp-reg-25.txt) &
# python run.py $(cat args/reg/exp-reg-26.txt) &
# python run.py $(cat args/reg_alt/exp-reg_alt-01.txt) &
# python run.py $(cat args/reg_alt/exp-reg_alt-02.txt) &
# python run.py $(cat args/reg_alt/exp-reg_alt-03.txt) &
# python run.py $(cat args/reg_alt/exp-reg_alt-04.txt) &
# python run.py $(cat args/reg_alt/exp-reg_alt-05.txt) &
# python run.py $(cat args/reg_alt/exp-reg_alt-06.txt) &
# python run.py $(cat args/reg_alt/exp-reg_alt-07.txt) &
# python run.py $(cat args/reg_alt/exp-reg_alt-08.txt) &
# python run.py $(cat args/reg_alt/exp-reg_alt-09.txt) &
# python run.py $(cat args/reg_alt/exp-reg_alt-10.txt) &
# python run.py $(cat args/reg_alt/exp-reg_alt-11.txt) &
# python run.py $(cat args/reg_alt/exp-reg_alt-12.txt) &
# python run.py $(cat args/reg_alt/exp-reg_alt-13.txt) &
# python run.py $(cat args/reg_alt/exp-reg_alt-14.txt) &
# python run.py $(cat args/reg_alt/exp-reg_alt-15.txt) &
# python run.py $(cat args/reg_alt/exp-reg_alt-16.txt) &
# python run.py $(cat args/reg_alt/exp-reg_alt-17.txt) &
# python run.py $(cat args/reg_alt/exp-reg_alt-18.txt) &
# python run.py $(cat args/reg_alt/exp-reg_alt-19.txt) &
# python run.py $(cat args/reg_alt/exp-reg_alt-20.txt) &
# python run.py $(cat args/reg_alt/exp-reg_alt-21.txt) &
# python run.py $(cat args/reg_alt/exp-reg_alt-22.txt) &
# python run.py $(cat args/reg_alt/exp-reg_alt-23.txt) &
# python run.py $(cat args/reg_alt/exp-reg_alt-24.txt) &
# python run.py $(cat args/reg_alt/exp-reg_alt-25.txt) &
# python run.py $(cat args/reg_alt/exp-reg_alt-26.txt) &
